version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'catalog'
    ports:
      - '5432:5432'

  catalog:
    image: 'item:latest'
    environment:
      APP_DB_HOST: 'postgres:5432'
      APP_REDIS_HOST: 'redisearch'
      APP_REDIS_PORT: 6379
      APP_REDIS_DB: 0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
      - 'redisearch'

  redisearch:
    image: 'redislabs/redisearch:latest'
    ports:
      - '6379:6379'
