name: Node + Docker builder

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: make lint
      - run: make check
      - run: make
      - run: make buildDev
      - run: make dockerBuild
